/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VisaoFechamentoLocacao.java
 *
 * Created on 24/11/2011, 01:18:06
 */
package locarrao.visao.grafica;

import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.dominio.Clientes;
import modelo.dominio.Locacao;
import modelo.persistencia.PersisteCliente;
import modelo.persistencia.PersisteLocacao;
import modelo.persistencia.PersisteModeloVeiculo;
import modelo.persistencia.PersisteMotorista;
import modelo.persistencia.PersisteVeiculos;

/**
 *
 * @author Magelinha
 */
public class VisaoFechamentoLocacao extends javax.swing.JFrame {
    
    Clientes cliente = new Clientes(); 
    PersisteLocacao persisteLocacao = new PersisteLocacao();
    PersisteCliente persisteCliente = new PersisteCliente();
    PersisteMotorista persisteMotorista = new PersisteMotorista();
    PersisteVeiculos persisteVeiculo = new PersisteVeiculos();
    /** Creates new form VisaoFechamentoLocacao */
    public VisaoFechamentoLocacao() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLocacoes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jBPesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fechamento de Locação");

        jTableLocacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Motorista", "Veículo", "Quilometragem de Saída", "Data de Saída"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableLocacoes);
        jTableLocacoes.getColumnModel().getColumn(0).setMinWidth(140);
        jTableLocacoes.getColumnModel().getColumn(1).setMinWidth(120);
        jTableLocacoes.getColumnModel().getColumn(2).setMinWidth(80);
        jTableLocacoes.getColumnModel().getColumn(3).setMinWidth(90);
        jTableLocacoes.getColumnModel().getColumn(4).setMinWidth(70);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabel1.setText("Código do Cliente*: ");

        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jBPesquisar)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisar))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("* O campo código é obrigatório!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(140, 140, 140))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        exibirResultado();
    }//GEN-LAST:event_jBPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VisaoFechamentoLocacao().setVisible(true);
            }
        });
    }
    
    public void exibirResultado(){
        pegarValor();
        buscarListaLocacoes(cliente);
    }
    public void buscarListaLocacoes(Clientes cliente){
        List<Locacao> lista = persisteLocacao.retornarLocacoesEmAbertoPorCliente(cliente);
        inserirNaTabela(lista);
    }
    
    public void inserirNaTabela(List<Locacao> lista){
        Object[] objeto = null;
        DefaultTableModel modelo = (DefaultTableModel)jTableLocacoes.getModel();
        SimpleDateFormat formataData = new SimpleDateFormat("dd/MM/yyyy");
        
        modelo.setRowCount(0);
        for(Locacao item: lista){
            objeto = new Object[]{persisteCliente.pesquisarClienteBD(item.getCliente()),
                                  persisteMotorista.pesquisarMotoristaBD(item.getMotorista()),
                                  persisteVeiculo.pesquisarVeiculoBD(item.getVeiculo()),
                                  item.getQuilometragemDeSaida(),
                                  formataData.format(item.getDataSaida())};
            
            modelo.addRow(objeto);
        }
    }
    public void pegarValor(){
        if(chamarVerificacoes()){
            cliente = new Clientes();
            cliente.setCodigo(Integer.valueOf(jTxtCodigo.getText()));
        }
    }
    
    public boolean chamarVerificacoes(){
        if(jTxtCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo código é obrigatório!");
            return false;
        }
        else if(!verificarEntrada()){
            JOptionPane.showMessageDialog(null, "O campo código so pode conter números");
            return false;
        }
        else{
            return true;
        }
    }
    
    public boolean verificarEntrada(){
        for(int i = 0; i < jTxtCodigo.getText().length();i++){
            if(!Character.isDigit(jTxtCodigo.getText().charAt(i))){
                return false;
            }
        }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLocacoes;
    private javax.swing.JTextField jTxtCodigo;
    // End of variables declaration//GEN-END:variables
}
