/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuRelatorios.java
 *
 * Created on Nov 12, 2011, 6:43:47 PM
 */
package locarrao.visao;

/**
 *
 * @author USER
 */
public class MenuRelatorios extends javax.swing.JFrame {

    /** Creates new form MenuRelatorios */
    public MenuRelatorios() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        locacaoAberto = new javax.swing.JRadioButton();
        locacaoFinalizada = new javax.swing.JRadioButton();
        veiculosDisponiveis = new javax.swing.JRadioButton();
        veiculosMaisProcurados = new javax.swing.JRadioButton();
        disponibilidadeTipoVeiculo = new javax.swing.JRadioButton();
        veiculosMaisRentaveis = new javax.swing.JRadioButton();
        buscaClientesPorNome = new javax.swing.JRadioButton();
        proximo = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relatórios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14))); // NOI18N

        buttonGroup1.add(locacaoAberto);
        locacaoAberto.setFont(new java.awt.Font("Tahoma", 0, 12));
        locacaoAberto.setText("Locações em aberto");

        buttonGroup1.add(locacaoFinalizada);
        locacaoFinalizada.setFont(new java.awt.Font("Tahoma", 0, 12));
        locacaoFinalizada.setText("Locações finalizadas");

        buttonGroup1.add(veiculosDisponiveis);
        veiculosDisponiveis.setFont(new java.awt.Font("Tahoma", 0, 12));
        veiculosDisponiveis.setText("Veículos disponíveis");

        buttonGroup1.add(veiculosMaisProcurados);
        veiculosMaisProcurados.setFont(new java.awt.Font("Tahoma", 0, 12));
        veiculosMaisProcurados.setText("Veículos mais procurados");

        buttonGroup1.add(disponibilidadeTipoVeiculo);
        disponibilidadeTipoVeiculo.setFont(new java.awt.Font("Tahoma", 0, 12));
        disponibilidadeTipoVeiculo.setText("Disponibilidade por tipo de veículo");

        buttonGroup1.add(veiculosMaisRentaveis);
        veiculosMaisRentaveis.setFont(new java.awt.Font("Tahoma", 0, 12));
        veiculosMaisRentaveis.setText("Veículos mais rentáveis");

        buttonGroup1.add(buscaClientesPorNome);
        buscaClientesPorNome.setFont(new java.awt.Font("Tahoma", 0, 12));
        buscaClientesPorNome.setText("Busca de clientes pelo nome");

        proximo.setText("Próximo");

        voltar.setText("Voltar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(voltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                                .addComponent(proximo))
                            .addComponent(locacaoAberto)
                            .addComponent(locacaoFinalizada)
                            .addComponent(veiculosDisponiveis)
                            .addComponent(veiculosMaisProcurados)
                            .addComponent(disponibilidadeTipoVeiculo)
                            .addComponent(veiculosMaisRentaveis)
                            .addComponent(buscaClientesPorNome)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {proximo, voltar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(locacaoAberto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locacaoFinalizada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(veiculosDisponiveis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(veiculosMaisProcurados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disponibilidadeTipoVeiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(veiculosMaisRentaveis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscaClientesPorNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proximo)
                    .addComponent(voltar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton buscaClientesPorNome;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton disponibilidadeTipoVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton locacaoAberto;
    private javax.swing.JRadioButton locacaoFinalizada;
    private javax.swing.JButton proximo;
    private javax.swing.JRadioButton veiculosDisponiveis;
    private javax.swing.JRadioButton veiculosMaisProcurados;
    private javax.swing.JRadioButton veiculosMaisRentaveis;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
